# Generated by Django 4.1.7 on 2023-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "attend",
                    models.CharField(
                        choices=[("Да", "Конечно приду!"), ("Нет", "К сожалению, нет")],
                        max_length=20,
                        verbose_name="Будет на свадьбе?",
                    ),
                ),
            ],
        ),
    ]
